### ISSUE TITLE
SetExpressCheckout failed: Unknown cipher in list: TLSv1(59)

### ISSUE THREAD

**Issue by Octolus** [sanwebe/Paypal-Express-Checkout-Example#3]
Keep getting this error. I am using "curl 7.19.7".

**Comment by Octolus** [comment]
Changed:
`curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');`

to

`curl_setopt($ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1);`

Now it's giving:

> Error : Security header is not valid
> Array
> (
>     [TIMESTAMP] => 2016%2d03%2d14T14%3a31%3a14Z
>     [CORRELATIONID] => c23dccba809ca
>     [ACK] => Failure
>     [VERSION] => 109%2e0
>     [BUILD] => 18316154
>     [L_ERRORCODE0] => 10002
>     [L_SHORTMESSAGE0] => Security%20error
>     [L_LONGMESSAGE0] => Security%20header%20is%20not%20valid
>     [L_SEVERITYCODE0] => Error
> )

**Comment by sanwebe** [comment]
Perhaps it's sslv3 handshake failure, try removing the line and adding the ssl version. 
curl_setopt($ch, CURLOPT_SSLVERSION, 4);
