### ISSUE TITLE
paypal.class.php Issue

### ISSUE THREAD

**Issue by Nihlus81** [sanwebe/Paypal-Express-Checkout-Example#4]
When ever i try to run this code on my server with my details set up i get this error and I'm not sure how to fix it

[12-Jul-2016 09:04:58 America/Denver] PHP Fatal error:  Can't use function return value in write context in on line 125

**Comment by Nihlus81** [comment]
Managed to fix this part by changing line 125 from:

> if(!empty(_SESSION('ppl_products'))&&!empty(_SESSION('ppl_charges'))){
> to
> if(_SESSION('ppl_products') === '' && _SESSION('ppl_charges') === ''){

its worked but now i am getting security errors

Error : Security header is not valid
Array
(
    [TIMESTAMP] => 2016%2d07%2d12T15%3a41%3a18Z
    [CORRELATIONID] => 89390649e83e3
    [ACK] => Failure
    [VERSION] => 109%2e0
    [BUILD] => 23255924
    [L_ERRORCODE0] => 10002
    [L_SHORTMESSAGE0] => Security%20error
    [L_LONGMESSAGE0] => Security%20header%20is%20not%20valid
    [L_SEVERITYCODE0] => Error
)

**Comment by Nihlus81** [comment]
Managed to sort this found that i had my live and sandbox details wrong way round in the config file

**Comment by snehakar** [comment]
Hii,,
if(_SESSION('ppl_products') === '' && _SESSION('ppl_charges') === ''){     this code also showing error. error is like this "SetExpressCheckout failed: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure(35)"  please help me how to solve this error.

**Comment by snehakar** [comment]
Testing Example is not working properly. It showing error, when i am testing this example.
