### ISSUE TITLE
Transaction ID

### ISSUE THREAD

**Issue by Nihlus81** [sanwebe/Paypal-Express-Checkout-Example#5]
Hi got the code working as it was really easy to work with, just having a problem finding a Transaction ID as I would like to save this next to my orders for reference but not where in the code can i find the variable send back from paypal.

Below is what gets send back but none of them are the transaction ID and in paypal.class.php in the function GetTransactionDetails in the commented out sql part there is $transactionID but this is not declared or populated anywhere in the function

Array
(
    [TOKEN] => EC%2d40L71427AV1373019
    [BILLINGAGREEMENTACCEPTEDSTATUS] => 0
    [CHECKOUTSTATUS] => PaymentActionNotInitiated
    [TIMESTAMP] => 2016%2d07%2d13T14%3a16%3a17Z
    [CORRELATIONID] => 9adeafb6bedb0
    [ACK] => Success
    [VERSION] => 109%2e0
    [BUILD] => 000000
    [EMAIL] => paypal%2dbuyer%40talkgeekytome%2eco%2euk
    [PAYERID] => 8PKYKN9GK7ZYU
    [PAYERSTATUS] => verified
    [FIRSTNAME] => test
    [LASTNAME] => buyer
    [COUNTRYCODE] => GB
    [ADDRESSSTATUS] => Confirmed
    [CURRENCYCODE] => GBP
    [AMT] => 22%2e00
    [ITEMAMT] => 22%2e00
    [SHIPPINGAMT] => 0%2e00
    [HANDLINGAMT] => 0%2e00
    [TAXAMT] => 0%2e00
    [INSURANCEAMT] => 0%2e00
    [SHIPDISCAMT] => 0%2e00
    [INSURANCEOPTIONOFFERED] => false
    [L_NAME1] => Test%20Plushy
    [L_NAME2] => Test%20Headband
    [L_NUMBER1] => 1
    [L_NUMBER2] => 2
    [L_QTY0] => 1
    [L_QTY1] => 1
    [L_QTY2] => 2
    [L_TAXAMT0] => 0%2e00
    [L_TAXAMT1] => 0%2e00
    [L_TAXAMT2] => 0%2e00
    [L_AMT0] => 0%2e00
    [L_AMT1] => 12%2e00
    [L_AMT2] => 5%2e00
    [L_DESC1] => Test%20Plushy
    [L_DESC2] => Test%20Headband
    [PAYMENTREQUEST_0_CURRENCYCODE] => GBP
    [PAYMENTREQUEST_0_AMT] => 22%2e00
    [PAYMENTREQUEST_0_ITEMAMT] => 22%2e00
    [PAYMENTREQUEST_0_SHIPPINGAMT] => 0%2e00
    [PAYMENTREQUEST_0_HANDLINGAMT] => 0%2e00
    [PAYMENTREQUEST_0_TAXAMT] => 0%2e00
    [PAYMENTREQUEST_0_INSURANCEAMT] => 0%2e00
    [PAYMENTREQUEST_0_SHIPDISCAMT] => 0%2e00
    [PAYMENTREQUEST_0_SELLERPAYPALACCOUNTID] => paypal%2dfacilitator%40talkgeekytome%2eco%2euk
    [PAYMENTREQUEST_0_INSURANCEOPTIONOFFERED] => false
    [PAYMENTREQUEST_0_ADDRESSSTATUS] => Confirmed
    [L_PAYMENTREQUEST_0_NAME1] => Test%20Plushy
    [L_PAYMENTREQUEST_0_NAME2] => Test%20Headband
    [L_PAYMENTREQUEST_0_NUMBER1] => 1
    [L_PAYMENTREQUEST_0_NUMBER2] => 2
    [L_PAYMENTREQUEST_0_QTY0] => 1
    [L_PAYMENTREQUEST_0_QTY1] => 1
    [L_PAYMENTREQUEST_0_QTY2] => 2
    [L_PAYMENTREQUEST_0_TAXAMT0] => 0%2e00
    [L_PAYMENTREQUEST_0_TAXAMT1] => 0%2e00
    [L_PAYMENTREQUEST_0_TAXAMT2] => 0%2e00
    [L_PAYMENTREQUEST_0_AMT0] => 0%2e00
    [L_PAYMENTREQUEST_0_AMT1] => 12%2e00
    [L_PAYMENTREQUEST_0_AMT2] => 5%2e00
    [L_PAYMENTREQUEST_0_DESC1] => Test%20Plushy
    [L_PAYMENTREQUEST_0_DESC2] => Test%20Headband
    [PAYMENTREQUESTINFO_0_ERRORCODE] => 0
)

**Comment by bateller** [comment]
It's working for me.

@Nihlus81 Try creating a new sandbox account.

Should get back:

> [TRANSACTIONID] => XXXXXX

Should also be the same as:

> [PAYMENTREQUEST_0_TRANSACTIONID] => XXXXXX

And:

> [PAYMENTREQUESTINFO_0_TRANSACTIONID] => XXXXXX

However, unfortunately the customer's `Unique Transaction ID #` doesn't appear to be passed.

**Comment by Nihlus81** [comment]
Hi

I managed to figure out what was wrong with it.

I was using the codes the wrong way around, I had the live codes on the
sand box page and sand box codes on the live page.

Many Thanks
Jon

**Comment by ag-coder** [comment]
and how i get the sales id?
https://cloud.githubusercontent.com/assets/1309895/9234578/44fbf76e-40ff-11e5-9c6d-7bfb7fd9ed5f.png
